//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HOADON
    {
        public string MASP { get; set; }
        public string MAHD { get; set; }
        public Nullable<int> DONGIA { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> THANHTIEN { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
