//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazada.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_LAZADA_MN : DbContext
    {
        public QL_LAZADA_MN()
            : base("name=QL_LAZADA_MN")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMIN> ADMINs { get; set; }
        public DbSet<CT_HOADON> CT_HOADON { get; set; }
        public DbSet<HOADON> HOADONs { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<KHUVUC> KHUVUCs { get; set; }
        public DbSet<LOAIHANG> LOAIHANGs { get; set; }
        public DbSet<MSdynamicsnapshotview> MSdynamicsnapshotviews { get; set; }
        public DbSet<MSmerge_dynamic_snapshots> MSmerge_dynamic_snapshots { get; set; }
        public DbSet<MSmerge_partition_groups> MSmerge_partition_groups { get; set; }
        public DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public DbSet<SANPHAM> SANPHAMs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TK_KHACHHANG> TK_KHACHHANG { get; set; }
        public DbSet<TK_NCC> TK_NCC { get; set; }
        public DbSet<MSdynamicsnapshotjob> MSdynamicsnapshotjobs { get; set; }
        public DbSet<MSmerge_agent_parameters> MSmerge_agent_parameters { get; set; }
        public DbSet<MSmerge_altsyncpartners> MSmerge_altsyncpartners { get; set; }
        public DbSet<MSmerge_articlehistory> MSmerge_articlehistory { get; set; }
        public DbSet<MSmerge_conflict_MIENNAM_ADMIN> MSmerge_conflict_MIENNAM_ADMIN { get; set; }
        public DbSet<MSmerge_conflict_MIENNAM_CT_HOADON> MSmerge_conflict_MIENNAM_CT_HOADON { get; set; }
        public DbSet<MSmerge_conflict_MIENNAM_HOADON> MSmerge_conflict_MIENNAM_HOADON { get; set; }
        public DbSet<MSmerge_conflict_MIENNAM_KHACHHANG> MSmerge_conflict_MIENNAM_KHACHHANG { get; set; }
        public DbSet<MSmerge_conflict_MIENNAM_KHUVUC> MSmerge_conflict_MIENNAM_KHUVUC { get; set; }
        public DbSet<MSmerge_conflict_MIENNAM_LOAIHANG> MSmerge_conflict_MIENNAM_LOAIHANG { get; set; }
        public DbSet<MSmerge_conflict_MIENNAM_NHACUNGCAP> MSmerge_conflict_MIENNAM_NHACUNGCAP { get; set; }
        public DbSet<MSmerge_conflict_MIENNAM_SANPHAM> MSmerge_conflict_MIENNAM_SANPHAM { get; set; }
        public DbSet<MSmerge_conflict_MIENNAM_sysdiagrams> MSmerge_conflict_MIENNAM_sysdiagrams { get; set; }
        public DbSet<MSmerge_conflict_MIENNAM_TK_KHACHHANG> MSmerge_conflict_MIENNAM_TK_KHACHHANG { get; set; }
        public DbSet<MSmerge_conflict_MIENNAM_TK_NCC> MSmerge_conflict_MIENNAM_TK_NCC { get; set; }
        public DbSet<MSmerge_conflicts_info> MSmerge_conflicts_info { get; set; }
        public DbSet<MSmerge_contents> MSmerge_contents { get; set; }
        public DbSet<MSmerge_current_partition_mappings> MSmerge_current_partition_mappings { get; set; }
        public DbSet<MSmerge_errorlineage> MSmerge_errorlineage { get; set; }
        public DbSet<MSmerge_generation_partition_mappings> MSmerge_generation_partition_mappings { get; set; }
        public DbSet<MSmerge_genhistory> MSmerge_genhistory { get; set; }
        public DbSet<MSmerge_history> MSmerge_history { get; set; }
        public DbSet<MSmerge_identity_range> MSmerge_identity_range { get; set; }
        public DbSet<MSmerge_log_files> MSmerge_log_files { get; set; }
        public DbSet<MSmerge_metadataaction_request> MSmerge_metadataaction_request { get; set; }
        public DbSet<MSmerge_past_partition_mappings> MSmerge_past_partition_mappings { get; set; }
        public DbSet<MSmerge_replinfo> MSmerge_replinfo { get; set; }
        public DbSet<MSmerge_sessions> MSmerge_sessions { get; set; }
        public DbSet<MSmerge_settingshistory> MSmerge_settingshistory { get; set; }
        public DbSet<MSmerge_supportability_settings> MSmerge_supportability_settings { get; set; }
        public DbSet<MSmerge_tombstone> MSmerge_tombstone { get; set; }
        public DbSet<MSrepl_errors> MSrepl_errors { get; set; }
        public DbSet<MSsnapshotdeliveryprogress> MSsnapshotdeliveryprogresses { get; set; }
        public DbSet<sysmergearticle> sysmergearticles { get; set; }
        public DbSet<sysmergepartitioninfo> sysmergepartitioninfoes { get; set; }
        public DbSet<sysmergepublication> sysmergepublications { get; set; }
        public DbSet<sysmergeschemaarticle> sysmergeschemaarticles { get; set; }
        public DbSet<sysmergeschemachange> sysmergeschemachanges { get; set; }
        public DbSet<sysmergesubscription> sysmergesubscriptions { get; set; }
        public DbSet<sysmergesubsetfilter> sysmergesubsetfilters { get; set; }
    }
}
