//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public KHACHHANG()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public string MAKH { get; set; }
        public string MAKV { get; set; }
        public string MATK_KH { get; set; }
        public string TENKH { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual KHUVUC KHUVUC { get; set; }
        public virtual TK_KHACHHANG TK_KHACHHANG { get; set; }
    }
}
