//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_conflict_MIENBAC_SANPHAM
    {
        public string MASP { get; set; }
        public string MANCC { get; set; }
        public string MALOAI { get; set; }
        public string TENSP { get; set; }
        public Nullable<int> DONGIA { get; set; }
        public string DVT { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string ANH { get; set; }
        public string MOTA { get; set; }
        public string KICHTHUOC { get; set; }
        public string TRONGLUONG { get; set; }
        public string MAUSAC { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<System.Guid> origin_datasource_id { get; set; }
    }
}
