//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSmerge_dynamic_snapshots
    {
        public int partition_id { get; set; }
        public string dynamic_snapshot_location { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public Nullable<System.DateTime> last_started { get; set; }
    
        public virtual MSmerge_partition_groups MSmerge_partition_groups { get; set; }
    }
}
