//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSsnapshotdeliveryprogress
    {
        public string session_token { get; set; }
        public int progress_token_hash { get; set; }
        public string progress_token { get; set; }
        public Nullable<System.DateTime> progress_timestamp { get; set; }
    }
}
