//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHACUNGCAP
    {
        public NHACUNGCAP()
        {
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
    
        public string MANCC { get; set; }
        public string MAKV { get; set; }
        public string MATK_NCC { get; set; }
        public string TENNCC { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual KHUVUC KHUVUC { get; set; }
        public virtual TK_NCC TK_NCC { get; set; }
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}
