//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysmergeschemachange
    {
        public System.Guid pubid { get; set; }
        public Nullable<System.Guid> artid { get; set; }
        public int schemaversion { get; set; }
        public System.Guid schemaguid { get; set; }
        public int schematype { get; set; }
        public string schematext { get; set; }
        public byte schemastatus { get; set; }
        public int schemasubtype { get; set; }
    }
}
