//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazada.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TK_NCC
    {
        public TK_NCC()
        {
            this.NHACUNGCAPs = new HashSet<NHACUNGCAP>();
        }
    
        public string MATK_NCC { get; set; }
        public string TENTK_NCC { get; set; }
        public string MK_KH { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual ICollection<NHACUNGCAP> NHACUNGCAPs { get; set; }
    }
}
