-- TẠO TÀI KHOẢN ĐĂNG NHẬP BẰNG QUYỀN SQL SERVER AUTHENTICATION
CREATE LOGIN AD004
WITH PASSWORD = '123',
DEFAULT_DATABASE = QL_LAZADA;
-- CẤP QUYỀN ĐĂNG NHẬP CHO USER
CREATE USER AD004 FOR LOGIN AD004 ;
-- TẠO NHÓM QUYỀN
EXEC sp_addrole 'NHOM_QUYEN_ADMIN';
-- GÁN USER VÀO NHÓM QUYỀN
EXEC sp_addrolemember 'NHOM_QUYEN_ADMIN', 'AD004';
-- GÁN QUYỀN VÀO NHÓM QUYỀN
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON CT_HOADON TO NHOM_QUYEN_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON HOADON TO NHOM_QUYEN_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON KHACHHANG TO NHOM_QUYEN_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON LOAIHANG TO NHOM_QUYEN_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON NHACUNGCAP TO NHOM_QUYEN_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON SANPHAM TO NHOM_QUYEN_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON TK_KHACHHANG TO NHOM_QUYEN_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON TK_NCC TO NHOM_QUYEN_ADMIN;

