-- TẠO TÀI KHOẢN ĐĂNG NHẬP BẰNG QUYỀN SQL SERVER AUTHENTICATION
CREATE LOGIN AD003
WITH PASSWORD = '123',
DEFAULT_DATABASE = QL_LAZADA;

CREATE LOGIN AD004
WITH PASSWORD = '123',
DEFAULT_DATABASE = QL_LAZADA;

-- CẤP QUYỀN ĐĂNG NHẬP CHO USER
 CREATE USER AD003 FOR LOGIN AD003 ;

 CREATE USER AD004 FOR LOGIN AD004 ;

-- TẠO NHÓM QUYỀN
EXEC sp_addrole 'NHOM_QUYEN_ADMIN';

EXEC sp_addrole 'NHOM_QUYEN_ADMIN_KHUVUC_MIENBAC';

-- GÁN NGƯỜI DÙNG VÀO NHÓM QUYỀN
EXEC sp_addrolemember 'NHOM_QUYEN_ADMIN', 'AD004';

EXEC sp_addrolemember 'NHOM_QUYEN_ADMIN_KHUVUC_MIENBAC', 'AD003';

-- QUYỀN CỦA ADMIN KHU VỰC
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON CT_HOADON TO NHOM_QUYEN_ADMIN_KHUVUC_MIENBAC;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON HOADON TO NHOM_QUYEN_ADMIN_KHUVUC_MIENBAC;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON KHACHHANG TO NHOM_QUYEN_ADMIN_KHUVUC_MIENBAC;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON LOAIHANG TO NHOM_QUYEN_ADMIN_KHUVUC_MIENBAC;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON NHACUNGCAP TO NHOM_QUYEN_ADMIN_KHUVUC_MIENBAC;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON SANPHAM TO NHOM_QUYEN_ADMIN_KHUVUC_MIENBAC;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON TK_KHACHHANG TO NHOM_QUYEN_ADMIN_KHUVUC_MIENBAC;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, ALTER ON TK_NCC TO NHOM_QUYEN_ADMIN_KHUVUC_MIENBAC;

---------------------------------------------------------------------------------------------------

-- QUYỀN CỦA ADMIN
GRANT SELECT ON CT_HOADON TO NHOM_QUYEN_ADMIN;
GRANT SELECT ON HOADON TO NHOM_QUYEN_ADMIN;
GRANT SELECT ON KHACHHANG TO NHOM_QUYEN_ADMIN;
GRANT SELECT ON LOAIHANG TO NHOM_QUYEN_ADMIN;
GRANT SELECT ON NHACUNGCAP TO NHOM_QUYEN_ADMIN;
GRANT SELECT ON SANPHAM TO NHOM_QUYEN_ADMIN;
GRANT SELECT ON TK_KHACHHANG TO NHOM_QUYEN_ADMIN;
GRANT SELECT ON TK_NCC TO NHOM_QUYEN_ADMIN;


